### ISSUE TITLE
Error on Generating Readings on MacOSX 10.15.4 Catalina

### ISSUE THREAD

**Issue by patrickvob** [jcsirot/anki-simple-furigana#4]
When clicking on "Generate Readings" button on anki, this error show up.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-29 18:29:17
Add-ons possibly involved: ⁨SimpleFurigana⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 89, in ensureOpen
    self.mecab = subprocess.Popen(
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
OSError: [Errno 86] Bad CPU type in executable: '/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/mecab/mecab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 273, in <lambda>
    lambda x: self._setHtml(x, callback, True))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 278, in _setHtml
    callback(self)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 63, in <lambda>
    Selection(editor, lambda s: action(editor, s))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 76, in generateRuby
    html = makeRuby(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 107, in makeRuby
    html = mecab.reading(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 98, in reading
    self.ensureOpen()
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 94, in ensureOpen
    raise Exception(
Exception: Please ensure your Linux system has 64 bit binary support.

**Comment by patrickvob** [comment]
Just for further clarification...
In Linux it works.

**Comment by patrickvob** [comment]
Still nothing on this?

**Comment by patrickvob** [comment]
I tried installing MeCab on my own on Mac OS X Catalina. Changing the executable path on reading.py, I got this.

`Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /Applications/Anki.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
JS error :1 Uncaught ReferenceError: $ is not defined
JS error :1 Uncaught ReferenceError: $ is not defined
accessing _ without importing from anki.lang will break in the future
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 54, in addButtons
    editor._addButton(None, "generateRuby", tip=_(

accessing _ without importing from anki.lang will break in the future
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 55, in addButtons
    u"Automatically generate furigana (Ctrl+F)"), label=_(u"Generate readings")),

accessing _ without importing from anki.lang will break in the future
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 56, in addButtons
    editor._addButton(None, "deleteRuby", tip=_(

accessing _ without importing from anki.lang will break in the future
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 57, in addButtons
    u"Mass delete furigana"), label=_(u"Delete readings"))

Caught exception:
Traceback (most recent call last):
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 273, in <lambda>
    lambda x: self._setHtml(x, callback, True))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 278, in _setHtml
    callback(self)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 63, in <lambda>
    Selection(editor, lambda s: action(editor, s))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 76, in generateRuby
    html = makeRuby(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 107, in makeRuby
    html = mecab.reading(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 108, in reading
    (kanji, reading) = re.match(r"(.+)\[(.*)\]", node).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

ignored late blur
Caught exception:
Traceback (most recent call last):
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 273, in <lambda>
    lambda x: self._setHtml(x, callback, True))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 278, in _setHtml
    callback(self)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 63, in <lambda>
    Selection(editor, lambda s: action(editor, s))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 76, in generateRuby
    html = makeRuby(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 107, in makeRuby
    html = mecab.reading(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 102, in reading
    self.mecab.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

ignored late blur
Caught exception:
Traceback (most recent call last):
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 273, in <lambda>
    lambda x: self._setHtml(x, callback, True))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 278, in _setHtml
    callback(self)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 63, in <lambda>
    Selection(editor, lambda s: action(editor, s))
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 76, in generateRuby
    html = makeRuby(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 107, in makeRuby
    html = mecab.reading(html)
  File "/Users/pvillela/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 102, in reading
    self.mecab.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe`

Sometimes one error, sometimes the other, always when clicking 'Generate Readings'

**Comment by jcsirot** [comment]
Fixed in version 1.0.0 which has been released on AnkiWeb
